Update egencache for multiple repos

diff --git a/etc/portage/postsync.d/egencache b/etc/portage/postsync.d/egencache
--- a/etc/portage/postsync.d/egencache
+++ b/etc/portage/postsync.d/egencache
@@ -2,10 +2,13 @@
 
 source /lib/gentoo/functions.sh
 
-einfo "Running egencache for local"
 
-if ! egencache --update -j6 --load-average 6.0 --repo local
-then
-	eerror "egencache failed!"
-	exit 1
-fi
+for repo in local local-haskell; do
+
+	einfo "Running egencache for $repo"
+
+	if ! egencache --update -j4 --load-average 4.0 --repo "$repo"
+		then
+		eerror "egencache failed!"
+		exit 1
+	fi
